name: Mise à jour titres FR

on:
  schedule:
    - cron: '5 * * * *'  # Toutes les heures à xx:05
  workflow_dispatch:      # Lancement manuel

jobs:
  update-news-francophone:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer feedparser
        run: pip install feedparser

      - name: Exécuter titres_fr.py
        run: python titres_fr.py

      - name: Commit titres_fr.json
        run: |
          git config user.name "Radio Augusta Bot"
          git config user.email "bot@radioaugusta.com"
          git add titres_fr.json
          git commit -m "🗞️ Mise à jour des titres francophones"
          git push
